import { useMemo, useState } from 'react';
import {
  AudioLines,
  CirclePlay,
  RefreshCw,
  RotateCcw,
  Search,
  Square,
} from 'lucide-react-native';
import { Pressable, Text, TextInput, View } from 'react-native';

import { palette, radius, spacing } from '@/design/tokens';
import type { VoiceSettingsController } from '@/voice/settings/contracts';
import {
  VOICE_PITCH_MAX,
  VOICE_PITCH_MIN,
  VOICE_RATE_MAX,
  VOICE_RATE_MIN,
  recommendedDeviceVoices,
  sortDeviceVoices,
} from '@/voice/settings/voice-preferences';
import {
  ActionButton,
  RangeSetting,
  SettingCard,
  SettingHeading,
} from '@/components/settings/voice-settings/setting-controls';
import {
  VoiceChoice,
  voiceDescription,
} from '@/components/settings/voice-settings/voice-choice';

export function VoiceSettings(props: { controller: VoiceSettingsController }) {
  const { controller } = props;
  const [browseAll, setBrowseAll] = useState(false);
  const [query, setQuery] = useState('');
  const sortedVoices = useMemo(
    () => sortDeviceVoices(controller.voices, controller.locale),
    [controller.locale, controller.voices],
  );
  const relevantVoices = recommendedDeviceVoices(
    controller.voices,
    controller.locale,
  );
  const selectedVoice = sortedVoices.find(
    (voice) => voice.identifier === controller.preferences.voiceId,
  );
  if (
    selectedVoice !== undefined &&
    !relevantVoices.some(
      (voice) => voice.identifier === selectedVoice.identifier,
    )
  ) {
    relevantVoices.push(selectedVoice);
  }
  const visibleVoices = (browseAll ? sortedVoices : relevantVoices).filter(
    (voice) =>
      query.trim().length === 0 ||
      `${voice.name} ${voice.language}`
        .toLowerCase()
        .includes(query.trim().toLowerCase()),
  );
  const effectiveVoiceName = controller.synthesis.enabled
    ? (controller.effectiveNeuralVoice ?? 'Vera neural voice')
    : (controller.effectiveVoice?.name ?? 'System voice');
  const selectedFallbackPreviewId = controller.preferences.voiceId ?? null;
  const neuralProviderName = displayProviderName(
    controller.synthesis.provider ?? 'neural speech',
  );

  return (
    <View style={{ gap: spacing.md }}>
      <View
        style={{
          gap: spacing.md,
          borderWidth: 1,
          borderColor: palette.accentLine,
          borderRadius: radius.lg,
          padding: spacing.lg,
          backgroundColor: palette.accentSurface,
        }}
      >
        <View
          style={{
            flexDirection: 'row',
            alignItems: 'center',
            gap: spacing.md,
          }}
        >
          <View
            style={{
              width: 46,
              height: 46,
              alignItems: 'center',
              justifyContent: 'center',
              borderWidth: 1,
              borderColor: palette.accentLine,
              borderRadius: radius.md,
              backgroundColor: palette.accentSurfaceStrong,
            }}
          >
            <AudioLines color={palette.accentStrong} size={23} />
          </View>
          <View style={{ minWidth: 0, flex: 1, gap: 3 }}>
            <Text
              selectable
              style={{ color: palette.text, fontSize: 18, fontWeight: '700' }}
            >
              Vera’s voice
            </Text>
            <Text
              selectable
              style={{ color: palette.textSoft, lineHeight: 19 }}
            >
              {controller.synthesis.loading
                ? 'Checking Vera’s speech service…'
                : controller.synthesis.unavailable
                  ? 'Neural speech service unavailable'
                  : controller.synthesis.enabled
                    ? `${effectiveVoiceName} · ${controller.synthesis.provider ?? 'neural speech'}`
                    : `${effectiveVoiceName} · ${controller.effectiveVoice?.language ?? controller.locale}`}
            </Text>
          </View>
        </View>
        <Text selectable style={{ color: palette.muted, lineHeight: 20 }}>
          {controller.synthesis.unavailable
            ? 'Vera could not reach the configured neural speech service. It will not silently change voices; retry the service check when Pocket TTS is available.'
            : controller.synthesis.enabled
              ? `Generated by ${controller.synthesis.model ?? 'Pocket TTS'} on Vera’s owner-controlled machine. This voice is used for Read aloud and live conversation.`
              : 'Neural speech is not enabled on this Vera server. Read aloud and live conversation currently use this device’s built-in fallback voice.'}
        </Text>
        {controller.synthesis.unavailable ? (
          <ActionButton
            icon={RefreshCw}
            label="Retry neural speech"
            onPress={() => void controller.refreshSynthesis()}
          />
        ) : null}
      </View>

      {controller.synthesis.enabled ? (
        <SettingCard>
          <SettingHeading
            eyebrow="NEURAL SPEECH"
            title="Choose Vera’s voice"
            description={`${String(controller.synthesis.voices.length)} neural voice${controller.synthesis.voices.length === 1 ? '' : 's'} advertised by ${controller.synthesis.provider ?? 'the configured speech provider'}. This selection controls Read aloud and live conversations on this device.`}
          />
          {!controller.selectedNeuralVoiceAvailable ? (
            <Text
              accessibilityRole="alert"
              selectable
              style={{ color: palette.warning, lineHeight: 19 }}
            >
              Your saved neural voice is no longer available. Vera is using the
              server default.
            </Text>
          ) : null}
          {controller.synthesis.voices.map((voice) => {
            const previewing =
              controller.previewing?.kind === 'neural' &&
              controller.previewing.voiceId === voice;
            return (
              <VoiceChoice
                description={
                  voice === controller.synthesis.voice
                    ? `Server default · generated locally by ${neuralProviderName}`
                    : `Generated locally by ${neuralProviderName}`
                }
                key={voice}
                name={displayVoiceName(voice)}
                previewLabel={
                  previewing
                    ? `Stop ${voice} preview`
                    : `Preview ${voice} neural voice`
                }
                previewing={previewing}
                recommended={voice === controller.synthesis.voice}
                selected={voice === controller.effectiveNeuralVoice}
                onPress={() => controller.update({ neuralVoiceId: voice })}
                onPreview={() =>
                  void (previewing
                    ? controller.stopPreview()
                    : controller.previewNeural(voice))
                }
              />
            );
          })}
        </SettingCard>
      ) : null}

      <SettingCard>
        <SettingHeading
          eyebrow="DEVICE FALLBACK"
          title="Fallback delivery"
          description="These controls apply only when neural speech is explicitly disabled. Previewing here always uses this device—not Pocket TTS."
        />
        {!controller.selectedFallbackVoiceAvailable ? (
          <Text
            accessibilityRole="alert"
            selectable
            style={{ color: palette.warning, lineHeight: 19 }}
          >
            Your saved fallback voice is not installed here. Vera is using the
            best available match until you choose another.
          </Text>
        ) : null}
        <RangeSetting
          label="Speaking speed"
          leftLabel="Slower"
          rightLabel="Faster"
          minimum={VOICE_RATE_MIN}
          maximum={VOICE_RATE_MAX}
          step={0.05}
          value={controller.preferences.rate}
          valueLabel={`${controller.preferences.rate.toFixed(2)}×`}
          onChange={(rate) => controller.update({ rate })}
        />
        <RangeSetting
          label="Voice pitch"
          leftLabel="Lower"
          rightLabel="Higher"
          minimum={VOICE_PITCH_MIN}
          maximum={VOICE_PITCH_MAX}
          step={0.05}
          value={controller.preferences.pitch}
          valueLabel={controller.preferences.pitch.toFixed(2)}
          onChange={(pitch) => controller.update({ pitch })}
        />
        <View
          style={{ flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }}
        >
          <ActionButton
            icon={
              controller.previewing?.kind === 'fallback' &&
              controller.previewing.voiceId === selectedFallbackPreviewId
                ? Square
                : CirclePlay
            }
            label={
              controller.previewing?.kind === 'fallback' &&
              controller.previewing.voiceId === selectedFallbackPreviewId
                ? 'Stop fallback preview'
                : 'Preview selected fallback'
            }
            primary
            onPress={() =>
              void (controller.previewing?.kind === 'fallback' &&
              controller.previewing.voiceId === selectedFallbackPreviewId
                ? controller.stopPreview()
                : controller.previewFallback())
            }
          />
          <ActionButton
            icon={RotateCcw}
            label="Reset"
            onPress={() => controller.reset()}
          />
        </View>
      </SettingCard>

      <SettingCard>
        <View
          style={{
            flexDirection: 'row',
            alignItems: 'flex-start',
            justifyContent: 'space-between',
            gap: spacing.md,
          }}
        >
          <SettingHeading
            eyebrow="DEVICE FALLBACK"
            title="Choose a fallback voice"
            description={
              controller.loadingVoices
                ? 'Looking for voices supplied by this operating system and browser…'
                : `${String(controller.voices.length)} system voice${controller.voices.length === 1 ? '' : 's'} reported by this device`
            }
          />
          <Pressable
            accessibilityLabel="Refresh installed voices"
            accessibilityRole="button"
            disabled={controller.loadingVoices}
            onPress={() =>
              void Promise.all([
                controller.refreshSynthesis(),
                controller.refreshVoices(),
              ])
            }
            style={({ pressed }) => ({
              width: 44,
              height: 44,
              alignItems: 'center',
              justifyContent: 'center',
              borderWidth: 1,
              borderColor: palette.line,
              borderRadius: radius.md,
              opacity: controller.loadingVoices ? 0.45 : pressed ? 0.65 : 1,
              backgroundColor: palette.surfaceRaised,
            })}
          >
            <RefreshCw color={palette.textSoft} size={18} />
          </Pressable>
        </View>

        <VoiceChoice
          description={`Uses the ${controller.locale} system default or an enhanced device voice when one is available.`}
          name="Automatic"
          recommended
          selected={controller.preferences.voiceId === undefined}
          onPress={() => controller.update({ voiceId: undefined })}
          previewLabel="Preview automatic fallback voice"
          previewing={
            controller.previewing?.kind === 'fallback' &&
            controller.previewing.voiceId === selectedFallbackPreviewId &&
            controller.preferences.voiceId === undefined
          }
          onPreview={() =>
            void (controller.previewing?.kind === 'fallback' &&
            controller.previewing.voiceId === selectedFallbackPreviewId &&
            controller.preferences.voiceId === undefined
              ? controller.stopPreview()
              : controller.previewFallback())
          }
        />

        {controller.voices.length === 0 && !controller.loadingVoices ? (
          <Text selectable style={{ color: palette.muted, lineHeight: 20 }}>
            Vera could not enumerate this device’s voices. Automatic mode will
            continue to use the operating system default.
          </Text>
        ) : null}

        {browseAll ? (
          <View
            style={{
              minHeight: 44,
              flexDirection: 'row',
              alignItems: 'center',
              gap: spacing.sm,
              borderWidth: 1,
              borderColor: palette.line,
              borderRadius: radius.md,
              paddingHorizontal: spacing.md,
              backgroundColor: palette.canvas,
            }}
          >
            <Search color={palette.faint} size={17} />
            <TextInput
              accessibilityLabel="Search installed voices"
              onChangeText={setQuery}
              placeholder="Search voices or languages"
              placeholderTextColor={palette.faint}
              style={{ minWidth: 0, flex: 1, color: palette.text }}
              value={query}
            />
          </View>
        ) : null}

        {!browseAll &&
        relevantVoices.length === 0 &&
        controller.voices.length > 0 ? (
          <Text selectable style={{ color: palette.muted, lineHeight: 20 }}>
            This device did not identify any enhanced voices. Automatic mode
            will use the operating system default; open the full catalog to
            choose a specific system voice.
          </Text>
        ) : null}

        {visibleVoices.map((voice) => (
          <VoiceChoice
            description={voiceDescription(voice)}
            key={voice.identifier}
            name={voice.name}
            recommended={
              voice.identifier === controller.effectiveVoice?.identifier &&
              controller.preferences.voiceId === undefined
            }
            selected={voice.identifier === controller.preferences.voiceId}
            onPress={() => controller.update({ voiceId: voice.identifier })}
            previewLabel={`Preview ${voice.name} as a device fallback`}
            previewing={
              controller.previewing?.kind === 'fallback' &&
              controller.previewing.voiceId === voice.identifier
            }
            onPreview={() =>
              void (controller.previewing?.kind === 'fallback' &&
              controller.previewing.voiceId === voice.identifier
                ? controller.stopPreview()
                : controller.previewFallback(voice.identifier))
            }
          />
        ))}

        {browseAll && visibleVoices.length === 0 ? (
          <Text
            selectable
            style={{ color: palette.muted, textAlign: 'center' }}
          >
            No installed voice matches that search.
          </Text>
        ) : null}

        {sortedVoices.length > relevantVoices.length ? (
          <ActionButton
            label={
              browseAll
                ? 'Show recommended languages'
                : `Browse all ${String(sortedVoices.length)} voices`
            }
            onPress={() => {
              setBrowseAll((current) => !current);
              setQuery('');
            }}
          />
        ) : null}
      </SettingCard>
    </View>
  );
}

function displayVoiceName(voice: string): string {
  return voice
    .split(/[-_]/u)
    .filter(Boolean)
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join(' ');
}

function displayProviderName(provider: string): string {
  return provider === 'pocket_tts'
    ? 'Pocket TTS'
    : provider.replaceAll('_', ' ');
}
